name: juju-txn-helper
version: '0.1' # just for humans, typically '1.2+git' or '1.3.2'
base: core18
summary: Juju transaction examination tool
description: |
  This snap contains a tool for examining the transaction queue (txn-queue)
  of a model.

grade: devel
confinement: devmode

parts:
  python:
    plugin: python
    requirements:
      - requirements.txt
    source: ./

apps:
  juju-txn-helper:
    command: txn_helper.py
